### ISSUE TITLE
Not really an issue, just the name

### ISSUE THREAD

**Issue by FlxVctr** [tw2113/tweetQuery#1]
Hi Michael,
sorry to bother you, but accidentally I named a tool I'm developing at the moment TweetQuery, too (not public yet). As your application seems to be deprecated, I don't think it's a big problem, but is it ok, if I take the name? (Nothing commercial, just for research.) Otherwise I just think up something else.
Cheers,
Felix

**Comment by tw2113** [comment]
Go for it. Hopefully it proves useful longer than mine did :D

**Comment by FlxVctr** [comment]
Thanks!
